/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _cocokeyboard_h_
#define _cocokeyboard_h_
//---------------------------------------------------------------------------------
extern const unsigned char cocokeyboard[];
extern const int cocokeyboard_size;
//---------------------------------------------------------------------------------
#endif //_cocokeyboard_h_
//---------------------------------------------------------------------------------
