/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _dragonkeyboard_h_
#define _dragonkeyboard_h_
//---------------------------------------------------------------------------------
extern const unsigned char dragonkeyboard[];
extern const int dragonkeyboard_size;
//---------------------------------------------------------------------------------
#endif //_dragonkeyboard_h_
//---------------------------------------------------------------------------------
